In [73]:
pip install  pyfaidx

Note: you may need to restart the kernel to use updated packages.


In [184]:
pip install torch

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/da/6a/7fb9d82db4568834ff6d4df2fe3b143de4ed65a3f8f93e7daed703626cb6/torch-2.1.2-cp311-cp311-manylinux1_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 31.3 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 38.9 MB/s eta 0:00:00m eta 0:00:010:01:01
  Obtaining dependency information for nvidia-cudnn-cu12==8.9.2.26 from https://files.pythonhosted.org/packages/ff/74/a2e2be7fb83aaedec84f391f082cf765dfb635e7caa9b49065f73e4835d8/nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 5.5 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 16.8 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 M

In [187]:
import pandas as pd
import numpy as np


# Convert fimo.tsv to bed format

In [94]:
# Load the TSV file into a DataFrame
#file_path=input("Give fimo.tsv file path: ")
file_path = '/mnt/raid1/thalassini/home/fimo/encode_grch38_max/fimo.tsv'
df = pd.read_csv(file_path, sep='\t')
df.dropna(inplace=True)

# Display the DataFrame
df

motif_id motif_alt_id sequence_name        start         stop strand  \
0       MA0139.2         CTCF         chr10      11458.0      11472.0      +   
1       MA0139.2         CTCF         chr12     547112.0     547126.0      -   
2       MA0139.2         CTCF          chr1     869920.0     869934.0      +   
3       MA0139.2         CTCF          chr1     904770.0     904784.0      +   
4       MA0139.2         CTCF          chr6    1397165.0    1397179.0      -   
...          ...          ...           ...          ...          ...    ...   
480300  MA0139.2         CTCF          chr1  245200915.0  245200929.0      -   
480301  MA0139.2         CTCF          chr1  245560998.0  245561012.0      +   
480302  MA0139.2         CTCF          chr1  246738775.0  246738789.0      +   
480303  MA0139.2         CTCF          chr1  247423982.0  247423996.0      +   
480304  MA0139.2         CTCF          chr1  247470114.0  247470128.0      +   

          score       p-value  q-value matched_sequence  
0       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
1       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
2       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
3       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
4       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
...         ...           ...      ...              ...  
480300  10.0984  4.490000e-05    0.548  ATCAACAGGGGTCAC  
480301  10.0984  4.490000e-05    0.548  AACAGAAGGTGGCCC  
480302  10.0984  4.490000e-05    0.548  CCCGCGAGGTGGAGG  
480303  10.0984  4.490000e-05    0.548  AGCAGGAGAGGGAGC  
480304  10.0984  4.490000e-05    0.548  ATCACAAGAGGTCAG  

[480305 rows x 10 columns]

## Rename columns


In [95]:
df.rename(columns={"sequence_name": "Chromosome", "start": "Start", "stop": "End"}, inplace=True)
df


motif_id motif_alt_id Chromosome        Start          End strand  \
0       MA0139.2         CTCF      chr10      11458.0      11472.0      +   
1       MA0139.2         CTCF      chr12     547112.0     547126.0      -   
2       MA0139.2         CTCF       chr1     869920.0     869934.0      +   
3       MA0139.2         CTCF       chr1     904770.0     904784.0      +   
4       MA0139.2         CTCF       chr6    1397165.0    1397179.0      -   
...          ...          ...        ...          ...          ...    ...   
480300  MA0139.2         CTCF       chr1  245200915.0  245200929.0      -   
480301  MA0139.2         CTCF       chr1  245560998.0  245561012.0      +   
480302  MA0139.2         CTCF       chr1  246738775.0  246738789.0      +   
480303  MA0139.2         CTCF       chr1  247423982.0  247423996.0      +   
480304  MA0139.2         CTCF       chr1  247470114.0  247470128.0      +   

          score       p-value  q-value matched_sequence  
0       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
1       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
2       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
3       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
4       24.2951  2.930000e-10    0.026  GCCACCAGGGGGCGC  
...         ...           ...      ...              ...  
480300  10.0984  4.490000e-05    0.548  ATCAACAGGGGTCAC  
480301  10.0984  4.490000e-05    0.548  AACAGAAGGTGGCCC  
480302  10.0984  4.490000e-05    0.548  CCCGCGAGGTGGAGG  
480303  10.0984  4.490000e-05    0.548  AGCAGGAGAGGGAGC  
480304  10.0984  4.490000e-05    0.548  ATCACAAGAGGTCAG  

[480305 rows x 10 columns]

## Convert coordinated to integers

In [96]:
df["Start"]=df["Start"].astype('int')
df["End"]=df["End"].astype('int')

## Merge "p-value, q-value & matched_sequence" in column "name" 

In [97]:
# Concatenate columns into a new 'name' column
df['name'] = df['motif_alt_id'].astype(str) + '_' + df['p-value'].astype(str) + '_' + df['q-value'].astype(str) + '_' + df['matched_sequence']

# Drop the original columns
df.drop(['motif_id', 'p-value', 'q-value', 'matched_sequence', 'motif_alt_id' ], axis=1, inplace=True)

# Display the updated DataFrame with the new 'name' column and without the original col
df

Chromosome      Start        End strand    score  \
0           chr10      11458      11472      +  24.2951   
1           chr12     547112     547126      -  24.2951   
2            chr1     869920     869934      +  24.2951   
3            chr1     904770     904784      +  24.2951   
4            chr6    1397165    1397179      -  24.2951   
...           ...        ...        ...    ...      ...   
480300       chr1  245200915  245200929      -  10.0984   
480301       chr1  245560998  245561012      +  10.0984   
480302       chr1  246738775  246738789      +  10.0984   
480303       chr1  247423982  247423996      +  10.0984   
480304       chr1  247470114  247470128      +  10.0984   

                                       name  
0       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
1       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
2       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
3       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
4       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
...                                     ...  
480300  CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC  
480301  CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC  
480302  CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG  
480303  CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC  
480304  CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG  

[480305 rows x 6 columns]

In [98]:
columns=df.columns
columns

Index(['Chromosome', 'Start', 'End', 'strand', 'score', 'name'], dtype='object')

 ## Filter from variant chromosome names
 

In [99]:
#Discover the unique sequence names in fimo.tsv
for sequence_name in df['Chromosome'].unique():
    print(sequence_name)

chr10
chr12
chr1
chr6
chr4
chrX
chr16
chr20
chr22
chr19
chr3
chr7
chr11
chr8
chr14
chr17
chr13
chr2
chr9
hm
chr18
chr14_KI270726v1_random
chr15
chr16_KI270728v1_random
chr21
chr22_KI270734v1_random
chr22_KI270731v1_random
chr1_KI270714v1_random
chr15_KI270727v1_random
chrEBV
chr11_KI270721v1_random
chr14_KI270723v1_random
chr17_GL000205v2_random
chrUn_GL000218v1
chr14_GL000194v1_random
chrUn_KI270744v1
chrUn_GL000213v1
chrUn_KI270745v1
chrUn_GL000195v1
chrUn_GL000219v1
chr1_KI270712v1_random
chrUn_KI270750v1
chrUn_KI270755v1
chrUn_KI270753v1
chr22_KI270733v1_random
chr1_KI270706v1_random
chrUn_KI270748v1
chrUn_KI270741v1
chr1_KI270711v1_random
chrUn_GL000224v1
chr1_KI270708v1_random
chr14_KI270722v1_random
chr1_KI270713v1_random
chr14_KI270725v1_random
chrUn_KI270749v1
chr9_KI270717v1_random
chr14_KI270724v1_random
chrUn_KI270752v1
chrUn_KI270435v1
chrUn_KI270743v1
chr4_GL000008v2_random
chr14_GL000009v2_random
chr5_GL000208v1_random
chr14_GL000225v1_random
chrUn_GL000216v2
chrUn_GL000

In [100]:
# Expected list of NCBI values
expected_list = ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12',
                 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']

# Filter rows based on 'NCBI' column values matching the expected list
df = df[df['Chromosome'].isin(expected_list)]

In [101]:
df

Chromosome      Start        End strand    score  \
0           chr10      11458      11472      +  24.2951   
1           chr12     547112     547126      -  24.2951   
2            chr1     869920     869934      +  24.2951   
3            chr1     904770     904784      +  24.2951   
4            chr6    1397165    1397179      -  24.2951   
...           ...        ...        ...    ...      ...   
480300       chr1  245200915  245200929      -  10.0984   
480301       chr1  245560998  245561012      +  10.0984   
480302       chr1  246738775  246738789      +  10.0984   
480303       chr1  247423982  247423996      +  10.0984   
480304       chr1  247470114  247470128      +  10.0984   

                                       name  
0       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
1       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
2       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
3       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
4       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
...                                     ...  
480300  CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC  
480301  CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC  
480302  CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG  
480303  CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC  
480304  CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG  

[451732 rows x 6 columns]

## Save df as .bed

In [102]:
# Save the csv file 
df.to_csv('fimo_full.bed', sep='\t', index=False, header=False)

# Mart to bed
Convert mart_export.txt to bed format 

In [103]:
import pandas as pd

# Load the TSV file into a DataFrame
#file_path=input("Give mart_export_unique.txt file path: ")
file_path = '/mnt/raid1/thalassini/home/Downloads/mart_export.txt'
mart_df = pd.read_csv(file_path, sep='\t')
mart_df.dropna(inplace=True)

# Display the DataFrame
mart_df

Chromosome/scaffold name  Start (bp)   End (bp) Feature type
0                            18    35116801   35120999     Enhancer
1                             6    90249202   90257999     Enhancer
2                             7    39894801   39895400     Enhancer
3                            15    63059401   63062399     Enhancer
4                             3   119868001  119868400     Enhancer
...                         ...         ...        ...          ...
305075                        8    98939200   98949401     Promoter
305076                        4    39364800   39367201     Promoter
305077                        X   152752601  152755400     Promoter
305078                       16    58495400   58496001     Promoter
305079                        7    38332400   38337001     Promoter

[305080 rows x 4 columns]

In [104]:
# Mapping table
mapping_table = {
    '1': 'chr1',
    '2': 'chr2',
    '3': 'chr3',
    '4': 'chr4',
    '5': 'chr5',
    '6': 'chr6',
    '7': 'chr7',
    '8': 'chr8',
    '9': 'chr9',
    '10': 'chr10',
    '11': 'chr11',
    '12': 'chr12',
    '13': 'chr13',
    '14': 'chr14',
    '15': 'chr15',
    '16': 'chr16',
    '17': 'chr17',
    '18': 'chr18',
    '19': 'chr19',
    '20': 'chr20',
    '21': 'chr21',
    '22': 'chr22',
    'X': 'chrX',
    'Y': 'chrY',
    'MT': 'chrM'
}

In [105]:
mart_df['Chromosome/scaffold name'] = mart_df['Chromosome/scaffold name'].map(mapping_table)
mart_df

Chromosome/scaffold name  Start (bp)   End (bp) Feature type
0                         chr18    35116801   35120999     Enhancer
1                          chr6    90249202   90257999     Enhancer
2                          chr7    39894801   39895400     Enhancer
3                         chr15    63059401   63062399     Enhancer
4                          chr3   119868001  119868400     Enhancer
...                         ...         ...        ...          ...
305075                     chr8    98939200   98949401     Promoter
305076                     chr4    39364800   39367201     Promoter
305077                     chrX   152752601  152755400     Promoter
305078                    chr16    58495400   58496001     Promoter
305079                     chr7    38332400   38337001     Promoter

[305080 rows x 4 columns]

In [106]:
# Save the csv file 
mart_df.to_csv('mart.bed', sep='\t', index=False, header=False)

# Run bedtools intesect to create filtered fimo
>> bedtools intersect -a /mnt/raid1/thalassini/home/Downloads/fimo_full.bed  -b /mnt/raid1/thalassini/home/Downloads/mart.bed > ensemlb_filtered_fimo.bed


# Display filtered_fimo df

In [107]:
# Load the BED file into a DataFrame
#file_path=input("Give ensemlb_filtered_fimo.bed file path: ")
file_path = '/mnt/raid1/thalassini/home/ensemlb_filtered_fimo.bed'
filtered_df = pd.read_csv(file_path, sep='\t')
filtered_df.dropna(inplace=True)
filtered_df.columns=columns
# Display the DataFrame
filtered_df

Chromosome      Start        End strand    score  \
0            chr1     869920     869934      +  24.2951   
1            chr1     904770     904784      +  24.2951   
2            chr6    1397165    1397179      -  24.2951   
3            chr4    1579280    1579294      -  24.2951   
4            chrX    9995929    9995943      +  24.2951   
...           ...        ...        ...    ...      ...   
104638       chr2  239339669  239339683      -  10.0984   
104639       chr2  241355101  241355115      +  10.0984   
104640       chr1  241396943  241396957      +  10.0984   
104641       chr2  241764826  241764840      -  10.0984   
104642       chr1  245200915  245200929      -  10.0984   

                                       name  
0       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
1       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
2       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
3       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
4       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
...                                     ...  
104638  CTCF_4.49e-05_0.548_GCCAGGAGATTGCAG  
104639  CTCF_4.49e-05_0.548_GCCACATGGTGACAG  
104640  CTCF_4.49e-05_0.548_GCCACATGGTGACAG  
104641  CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC  
104642  CTCF_4.49e-05_0.548_ATCAACAGGGGTCAC  

[104643 rows x 6 columns]

In [70]:
print(f" The promoter/enhancer filtered data is reduced by {100-len(filtered_df)* 100/len(df)}% from initial fimo results")

 The promoter/enhancer filtered data is reduced by 76.8351588995245% from initial fimo results


# Run bedtools intesect to create chipseq_filtered fimo
>> bedtools intersect -a ensemlb_filtered_fimo.bed -b /mnt/raid1/thalassini/home/Downloads/ENCFF970MXD.bed > chipseq_filtered.bed

# Display chipseq_filtered df

In [108]:
# Load the BED file into a DataFrame
#file_path=input("Give chipseq_filtered_fimo.bed file path: ")
file_path = '/mnt/raid1/thalassini/home/chipseq_filtered.bed'
chipseq_filtered_df = pd.read_csv(file_path, sep='\t')
chipseq_filtered_df.dropna(inplace=True)
chipseq_filtered_df.columns=columns
# Display the DataFrame
chipseq_filtered_df

Chromosome      Start        End strand    score  \
0           chr1     869920     869934      +  24.2951   
1           chr1     904770     904784      +  24.2951   
2           chr6    1397165    1397179      -  24.2951   
3           chr4    1579280    1579294      -  24.2951   
4           chrX    9995929    9995943      +  24.2951   
...          ...        ...        ...    ...      ...   
17931       chr4  112637587  112637601      +  10.0984   
17932       chr9  122810697  122810711      -  10.0984   
17933       chr9  122810697  122810711      -  10.0984   
17934       chr7  131581578  131581592      +  10.0984   
17935       chr8  143771853  143771867      +  10.0984   

                                      name  
0      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
1      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
2      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
3      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
4      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
...                                    ...  
17931  CTCF_4.49e-05_0.548_GCCAGAAGATAGCGA  
17932  CTCF_4.49e-05_0.548_ACCACAATAGGGCAG  
17933  CTCF_4.49e-05_0.548_ACCACAATAGGGCAG  
17934  CTCF_4.49e-05_0.548_GCCAACAAAGGGCAG  
17935  CTCF_4.49e-05_0.548_AGCAGGAGGAGGCGG  

[17936 rows x 6 columns]

In [125]:
for chromosome in chipseq_filtered_df["Chromosome"]:
    print(chipseq_filtered)

0        chr1
1        chr1
2        chr6
3        chr4
4        chrX
         ... 
17931    chr4
17932    chr9
17933    chr9
17934    chr7
17935    chr8
Name: Chromosome, Length: 17936, dtype: object

In [72]:
print(f" The chipseq filtered data is reduced by {100-len(chipseq_filtered_df)* 100/len(df)}% from initial fimo results")

 The chipseq filtered data is reduced by 96.02950421931588% from initial fimo results


# Find sequence from coordinates

In [74]:
#/home/marina/Downloads/phix.fasta
from pyfaidx import Fasta

# Path to your reference genome FASTA file
reference_genome_file = '/mnt/raid1/thalassini/home/Downloads/Homo_sapiens.GRCh38.dna.toplevel.fa'



# Load the reference genome using pyfaidx
fasta = Fasta(reference_genome_file)

# List all chromosome names in the reference genome file
chromosome_names = fasta.keys()

# Display the list of chromosome names
print(chromosome_names)



odict_keys(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT', 'HG76_PATCH', 'HG2365_PATCH', 'HSCHR15_4_CTG8', 'HSCHR6_MHC_SSTO_CTG1', 'HSCHR6_MHC_MCF_CTG1', 'HSCHR6_MHC_COX_CTG1', 'HSCHR6_MHC_MANN_CTG1', 'HSCHR6_MHC_APD_CTG1', 'HSCHR6_MHC_QBL_CTG1', 'HSCHR6_MHC_DBB_CTG1', 'HSCHR17_7_CTG4', 'HSCHR16_1_CTG1', 'HSCHR15_6_CTG8', 'HG926_PATCH', 'HSCHR17_1_CTG5', 'HSCHR5_2_CTG1_1', 'HG1343_HG173_HG459_PATCH', 'HSCHR14_7_CTG1', 'HSCHR17_2_CTG5', 'HSCHR14_3_CTG1', 'HG2280_PATCH', 'HSCHR5_1_CTG1_1', 'HSCHR7_2_CTG6', 'HSCHR19LRC_LRC_J_CTG3_1', 'HSCHR19_4_CTG3_1', 'HSCHR19LRC_LRC_S_CTG3_1', 'HSCHR19LRC_LRC_I_CTG3_1', 'HG1815_PATCH', 'HG2265_PATCH', 'HSCHR19LRC_LRC_T_CTG3_1', 'HSCHR19LRC_COX1_CTG3_1', 'HSCHR19LRC_PGF1_CTG3_1', 'HSCHR8_8_CTG1', 'HG2275_PATCH', 'HSCHR1_3_CTG32_1', 'HSCHR6_1_CTG8', 'HG1532_PATCH', 'HSCHR1_5_CTG31', 'HSCHR19LRC_PGF2_CTG3_1', 'HSCHR19LRC_COX2_CTG3_1', 'HG2526_HG2573_PATCH', 'HG1_PA

In [124]:
# Replace the first 25 keys with mapping_table values
updated_fasta = {}

count = 0
for k, v in fasta.items():
    if count < 25:
        updated_fasta[mapping_table.get(k, k)] = v
        count += 1
    else:
        updated_fasta[k] = v
        


# Create true positive set

In [132]:
true_positives=[]
# Loop through the DataFrame and retrieve values of 'Chromosome', 'Start', and 'End' columns for each row
for index, row in chipseq_filtered_df.iterrows():
    chromosome = row['Chromosome']
    start = row['Start']
    end = row['End']
    true_positives.append(updated_fasta[chromosome][start-100:end+100].seq)
    


In [131]:
true_positives[1]

'CGCGGCCGCCTCCTCCTCCGAACGTGGCCGCCTCCGAACGTGGCCGCCGCCTCCTCCGAACGTGGCCGCTTCCGCAGCGCCCGGCGCAGGCCGCACTCCGCCACCAGGGGGCGCCACAGCTCCTCGCGCCGCCGCCTCCCGCAAACACAAAGAGCCGCGCGGCCACGACGGCCGCGTGCCCGGAGCGCCGGGGTCTTTCCTGGGCTCCAAAGTC'

# Create true negative set

## Create negative df by excluding the rows that belong to the ensembl_filtered df 

In [139]:
# Merge the DataFrames based on specific columns and keep rows that do not exist in df_filtered
merged = df.merge(filtered_df, on=['Chromosome', 'Start', 'End', 'strand', 'score', 'name'], how='outer', indicator=True)
negative_df = merged[merged['_merge'] == 'left_only'].drop('_merge', axis=1)



In [140]:
negative_df

Chromosome      Start        End strand    score  \
0           chr10      11458      11472      +  24.2951   
1           chr12     547112     547126      -  24.2951   
6            chr4    5821787    5821801      +  24.2951   
7            chr1    9495407    9495421      +  24.2951   
10          chr16   12095359   12095373      +  24.2951   
...           ...        ...        ...    ...      ...   
451726       chr1  243056957  243056971      +  10.0984   
451728       chr1  245560998  245561012      +  10.0984   
451729       chr1  246738775  246738789      +  10.0984   
451730       chr1  247423982  247423996      +  10.0984   
451731       chr1  247470114  247470128      +  10.0984   

                                       name  
0       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
1       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
6       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
7       CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
10      CTCF_2.93e-10_0.026_GCCACCAGGGGGCGC  
...                                     ...  
451726  CTCF_4.49e-05_0.548_GCCTGGAGGGGCCAC  
451728  CTCF_4.49e-05_0.548_AACAGAAGGTGGCCC  
451729  CTCF_4.49e-05_0.548_CCCGCGAGGTGGAGG  
451730  CTCF_4.49e-05_0.548_AGCAGGAGAGGGAGC  
451731  CTCF_4.49e-05_0.548_ATCACAAGAGGTCAG  

[348702 rows x 6 columns]

In [141]:
print(f"The percentage of the true negative set is {len(negative_df)/len(df)*100}% of the fimo results")

The percentage of the true negative set is 77.19222902074682% of the fimo results


In [142]:
true_negatives=[]
# Loop through the DataFrame and retrieve values of 'Chromosome', 'Start', and 'End' columns for each row
for index, row in negative_df.iterrows():
    chromosome = row['Chromosome']
    start = row['Start']
    end = row['End']
    true_negatives.append(updated_fasta[chromosome][start-100:end+100].seq)
    


In [150]:
print(f"We have {len(true_negatives)} negative sequences and {len(true_positives)} positive sequences")

We have 348702 negative sequences and 17936 positive sequences


In [145]:
print(f"True positives are {len(true_positives)/(len(true_negatives)+len(true_positives))*100}% of the dataset")

True positives are 4.892018830563117% of the dataset


In [146]:
print(f"True negatives are {len(true_negatives)/(len(true_negatives)+len(true_positives))*100}% of the dataset")

True negatives are 95.10798116943688% of the dataset


## Checking the length of the sequences

In [151]:
# Check the length of each string in the list
lengths_pos = [len(item) for item in true_positives]

In [158]:
max(lengths_pos),min(lengths_pos)

(214, 201)

In [159]:
# Check the length of each string in the list
lengths_neg = [len(item) for item in true_negatives]

In [ ]:
max(lengths_neg),min(lengths_neg)

# Combine the two sets in a df

In [161]:

# Create DataFrames for negative and positive sequences
true_negatives_df = pd.DataFrame({'data': true_negatives, 'class': 0})
true_positives_df= pd.DataFrame({'data': true_positives, 'class': 1})

# Concatenate both DataFrames into a single DataFrame
combined_df = pd.concat([true_negatives_df, true_positives_df], ignore_index=True)

# Display the combined DataFrame
print(combined_df)

                                                     data  class
0       GCCCCTGGGCCACGCCCACTCCCCCAAGCGGGGAAGGAGCTTCGCG...      0
1       CACCCACAACAGCCTGGACCCCGGACCGAGGTCCCCCTCGGTCGTC...      0
2       AAAACACTGACAGGAAAAGGGATGGACATGATTCCCAGAATCCTTC...      0
3       TAGTAGGTCATACCGCAGTGCCCACCGCAAGGGTGGCCACTGCGGA...      0
4       AGTTAATTTCGTTTGAATATATGGTTATTTGGGAGCTGGAGGTTGC...      0
...                                                   ...    ...
366633  CGGCCTATGACGGCGTCCTTGCGGAAGTACGGGTGCCGAGAGAAGC...      1
366634  TTGATCTTGTTTGTTACCTGGTTCTCAGTGAGCATAGGTAGTAGAC...      1
366635  TTGATCTTGTTTGTTACCTGGTTCTCAGTGAGCATAGGTAGTAGAC...      1
366636  CACCCGTTTCTATATTGAGGAGCTCCTCTCCATAAATAAAGCACAG...      1
366637  GGGGCGGTGGCGCGGAGTGGGCGGTGACTTCGGCGGGCGCCTCCCA...      1

[366638 rows x 2 columns]


In [219]:
# Export the DataFrame to a CSV file
combined_df.to_csv('data.csv', index=False)

In [176]:
# Shuffle the rows of the DataFrame
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [167]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, MaxPooling1D, Flatten, Dense




# Tokenizing sequences and converting to sequences of integers
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(combined_df['data'])
sequences = tokenizer.texts_to_sequences(combined_df['data'])



# Perform one-hot encoding for the padded sequences
#one_hot_sequences = np.array([one_hot_encode(seq) for seq in combined_df['data']])

In [ ]:
def one_hot_encode(sequence):
    encoding = {'A': [1, 0, 0, 0], 'T': [0, 1, 0, 0], 'G': [0, 0, 1, 0], 'C': [0, 0, 0, 1]}
    one_hot_sequence = [encoding.get(base, [0, 0, 0, 0]) for base in sequence]
    return np.array(one_hot_sequence)

In [193]:
# Find the maximum length of sequences
max_length = max(len(seq) for seq in combined_df['data'])

# Pad sequences to ensure they all have the same length
padded_sequences = [seq.ljust(max_length, 'N') for seq in combined_df['data']]

In [202]:
X= [one_hot_encode(sequence) for sequence in padded_sequences]
X=np.array(X)

In [203]:
y=np.array(combined_df['class'])

In [204]:
import torch
X = torch.from_numpy(X).type(torch.float)
y = torch.from_numpy(y).type(torch.float)

# View the first five samples
X[:5], y[:5]

(tensor([[[0., 0., 1., 0.],
          [1., 0., 0., 0.],
          [0., 1., 0., 0.],
          ...,
          [0., 1., 0., 0.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.]],
 
         [[0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 1., 0., 0.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.]],
 
         [[0., 0., 0., 1.],
          [0., 0., 0., 1.],
          [0., 0., 0., 1.],
          ...,
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.]],
 
         [[0., 1., 0., 0.],
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 0., 1., 0.],
          [0., 0., 1., 0.],
          [0., 1., 0., 0.]],
 
         [[0., 0., 0., 1.],
          [0., 1., 0., 0.],
          [0., 0., 1., 0.],
          ...,
          [0., 0., 1., 0.],
          [1., 0., 0., 0.],
          [0., 0., 1., 0.]]]),
 tensor([0., 0., 0., 0., 0.]))

In [208]:
# Split data into train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, # 20% test, 80% train
                                                    random_state=42) # make the random split reproducible

len(X_train), len(X_test), len(y_train), len(y_test)

(293310, 73328, 293310, 73328)

# Set up device agnostic code

In [206]:
# Standard PyTorch imports
import torch
from torch import nn

# Make device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [212]:
# 1. Construct a model class that subclasses nn.Module
class ModelV0(nn.Module):
    def __init__(self):
        super().__init__()
        # 2. Create 2 nn.Linear layers capable of handling X and y input and output shapes
        self.layer_1 = nn.Linear(in_features=4, out_features=5) # takes in 2 features (X), produces 5 features
        self.layer_2 = nn.Linear(in_features=5, out_features=1) # takes in 5 features, produces 1 feature (y)
    
    # 3. Define a forward method containing the forward pass computation
    def forward(self, x):
        # Return the output of layer_2, a single feature, the same shape as y
        return self.layer_2(self.layer_1(x)) # computation goes through layer_1 first then the output of layer_1 goes through layer_2

# 4. Create an instance of the model and send it to target device
model_0 = ModelV0().to(device)
model_0


ModelV0(
  (layer_1): Linear(in_features=4, out_features=5, bias=True)
  (layer_2): Linear(in_features=5, out_features=1, bias=True)
)

# Set up loss function and optimizer

In [213]:
# Create a loss function
# loss_fn = nn.BCELoss() # BCELoss = no sigmoid built-in
loss_fn = nn.BCEWithLogitsLoss() # BCEWithLogitsLoss = sigmoid built-in

# Create an optimizer
optimizer = torch.optim.SGD(params=model_0.parameters(), 
                            lr=0.1)

In [220]:
# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [221]:
from sklearn.metrics import balanced_accuracy_score

# Function to calculate balanced accuracy
def balanced_accuracy(y_true, y_pred):
    return balanced_accuracy_score(y_true, y_pred) * 100

# Train the model

In [215]:
# View the frist 5 outputs of the forward pass on the test data
y_logits = model_0(X_test.to(device))[:5]
y_logits

tensor([[[-0.1812],
         [-0.4116],
         [-0.4116],
         ...,
         [-0.5166],
         [-0.5166],
         [-0.0459]],

        [[-0.4116],
         [-0.5166],
         [-0.4116],
         ...,
         [-0.4116],
         [-0.4116],
         [-0.4116]],

        [[-0.1812],
         [-0.4116],
         [-0.4116],
         ...,
         [-0.0459],
         [-0.4116],
         [-0.0459]],

        [[-0.0459],
         [-0.1812],
         [-0.5166],
         ...,
         [-0.0459],
         [-0.4116],
         [-0.4116]],

        [[-0.1812],
         [-0.1812],
         [-0.1812],
         ...,
         [-0.1812],
         [-0.5166],
         [-0.1812]]], grad_fn=<SliceBackward0>)

In [216]:
# Use sigmoid on model logits
y_pred_probs = torch.sigmoid(y_logits)
y_pred_probs

tensor([[[0.4548],
         [0.3985],
         [0.3985],
         ...,
         [0.3736],
         [0.3736],
         [0.4885]],

        [[0.3985],
         [0.3736],
         [0.3985],
         ...,
         [0.3985],
         [0.3985],
         [0.3985]],

        [[0.4548],
         [0.3985],
         [0.3985],
         ...,
         [0.4885],
         [0.3985],
         [0.4885]],

        [[0.4885],
         [0.4548],
         [0.3736],
         ...,
         [0.4885],
         [0.3985],
         [0.3985]],

        [[0.4548],
         [0.4548],
         [0.4548],
         ...,
         [0.4548],
         [0.3736],
         [0.4548]]], grad_fn=<SigmoidBackward0>)

In [217]:
# Find the predicted labels (round the prediction probabilities)
y_preds = torch.round(y_pred_probs)

# In full
y_pred_labels = torch.round(torch.sigmoid(model_0(X_test.to(device))[:5]))

# Check for equality
print(torch.eq(y_preds.squeeze(), y_pred_labels.squeeze()))

# Get rid of extra dimension
y_preds.squeeze()

tensor([[True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True],
        [True, True, True,  ..., True, True, True]])


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<SqueezeBackward0>)

In [218]:
y_test[:5]

tensor([1., 0., 0., 0., 0.])